name: Semantic Release Dry Run

on:
  repository_dispatch:
    types: [gren]
    
jobs:
  gren-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set up Node.js v12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      - name: Set up Gren
        run: npm install github-release-notes -g
      - name: Generate Release Notes
        run: gren release --token=${{ secrets.GITHUB_TOKEN }} --override --prefix=v 
